# Generated by Django 3.2.4 on 2021-11-10 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StockWinner',
            new_name='StockGainer',
        ),
        migrations.RenameField(
            model_name='pricedata',
            old_name='stock',
            new_name='stock_id',
        ),
        migrations.RenameField(
            model_name='stockarticle',
            old_name='stock',
            new_name='stock_id',
        ),
        migrations.RenameField(
            model_name='stockgainer',
            old_name='stock',
            new_name='stock_id',
        ),
        migrations.RenameField(
            model_name='stockloser',
            old_name='stock',
            new_name='stock_id',
        ),
        migrations.RenameField(
            model_name='stocksymbol',
            old_name='stock_symbol',
            new_name='name',
        ),
    ]
