# Generated by Django 3.2.4 on 2022-01-07 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_auto_20211110_1705'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pricedata',
            old_name='stock_id',
            new_name='stock',
        ),
        migrations.RenameField(
            model_name='stockarticle',
            old_name='stock_id',
            new_name='stock',
        ),
        migrations.RenameField(
            model_name='stockgainer',
            old_name='stock_id',
            new_name='stock',
        ),
        migrations.RenameField(
            model_name='stockloser',
            old_name='stock_id',
            new_name='stock',
        ),
    ]
