# Generated by Django 3.2.4 on 2022-01-07 17:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_auto_20220107_0531'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricedata',
            name='date',
            field=models.DateField(default=datetime.datetime(1800, 1, 1, 0, 0)),
        ),
        migrations.AddField(
            model_name='pricedata',
            name='high',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='pricedata',
            name='low',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='pricedata',
            name='volume',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='stockarticle',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockarticle',
            name='date',
            field=models.DateField(default=datetime.datetime(1800, 1, 1, 0, 0)),
        ),
        migrations.AddField(
            model_name='stockarticle',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockarticle',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='stockarticle',
            name='scraper',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='stockarticle',
            name='sentiment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='stockarticle',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockgainer',
            name='avg_3_month_volume',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='stockgainer',
            name='change_percentage',
            field=models.DecimalField(decimal_places=2, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='stockgainer',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(1800, 1, 1, 0, 0)),
        ),
        migrations.AddField(
            model_name='stockgainer',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='stockgainer',
            name='trade_volume',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='stockloser',
            name='avg_3_month_volume',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='stockloser',
            name='change_percentage',
            field=models.DecimalField(decimal_places=2, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='stockloser',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(1800, 1, 1, 0, 0)),
        ),
        migrations.AddField(
            model_name='stockloser',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='stockloser',
            name='trade_volume',
            field=models.BigIntegerField(null=True),
        ),
    ]
