# Generated by Django 3.2.4 on 2022-01-09 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_auto_20220107_1752'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockarticle',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='stockgainer',
            options={'ordering': ['-date', '-change_percentage']},
        ),
        migrations.AlterModelOptions(
            name='stockloser',
            options={'ordering': ['-date', 'change_percentage']},
        ),
        migrations.RemoveField(
            model_name='pricedata',
            name='high',
        ),
        migrations.RemoveField(
            model_name='pricedata',
            name='low',
        ),
        migrations.AddField(
            model_name='pricedata',
            name='close',
            field=models.DecimalField(decimal_places=4, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='pricedata',
            name='open',
            field=models.DecimalField(decimal_places=4, max_digits=20, null=True),
        ),
    ]
