# Generated by Django 3.2.4 on 2022-01-29 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0006_auto_20220109_0533'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stocksymbol',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='stocksymbol',
            name='user_selected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='pricedata',
            constraint=models.UniqueConstraint(fields=('stock', 'date'), name='unique_price_data'),
        ),
        migrations.AddConstraint(
            model_name='stockarticle',
            constraint=models.UniqueConstraint(fields=('stock', 'date', 'name'), name='unique_article'),
        ),
        migrations.AddConstraint(
            model_name='stockgainer',
            constraint=models.UniqueConstraint(fields=('stock', 'date'), name='unique_gaining_stock'),
        ),
        migrations.AddConstraint(
            model_name='stockloser',
            constraint=models.UniqueConstraint(fields=('stock', 'date'), name='unique_losing_stock'),
        ),
        migrations.AddConstraint(
            model_name='stocksymbol',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_stock_ticker'),
        ),
    ]
