version: '3'
 
services:
  django:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: >
      sh -c "python3 manage.py migrate &&
             python3 manage.py wait_for_db &&
             python3 manage.py runserver 0.0.0.0:8000"
 
    environment:
      - DB_HOST=db
      - DB_NAME=stock_project_database
      - DB_USER=stock_project_database_user
      - DB_PASS=test
      - DEBUG=1
      - CELERY_BROKER=redis://redis:6379/0
    depends_on:
      - db        
  db:
    image: postgres:14
    environment:
      - POSTGRES_DB=stock_project_database
      - POSTGRES_USER=stock_project_database_user
      - POSTGRES_PASSWORD=test
  redis:
    image: redis
  celery:
    restart: always
    build:
      context: .
    command: celery -A mysite worker -l INFO
    volumes:
      - .:/app
    environment:
      - DB_HOST=db
      - DB_NAME=stock_project_database
      - DB_USER=stock_project_database_user
      - DB_PASS=test
      - CELERY_BROKER=redis://redis:6379/0
    depends_on:
      - db
      - redis
      - django